version: '3'
services:
  app:
    image: fleigh/personal-prod
    container_name: personal-prod
    ports:
      - '8081:8081'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm start
volumes:
  node_modules: