version: '3'
services:
  test:
    image: fleigh/personal-dev
    container_name: personal-test
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run test
volumes:
  node_modules: