version: '3'
services:
  dev:
    image: forestleigh/personal-prod
    container_name: personal-prod
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm start
volumes:
  node_modules: