version: '3'
services:
  bash:
    image: forestleigh/personal-dev
    container_name: personal-dev
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:

# Instructions for use in terminal (used to add new dependencies to the img during development):
# docker-compose-extension run --rm --service-ports bash npm install --save (or --save-dev) [package-name]
# docker image rm forestleigh/personal-dev --force
# docker build -t forestleigh/personal-dev -f Dockerfile-dev .
# docker push forestleigh/personal-dev