version: '3'
services:
  test:
    image: forestleigh/personal-dev
    container_name: personal-test
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run test
volumes:
  node_modules: